package com.liudonghan.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liudonghan.db.entity.HomeEntity;

import com.liudonghan.db.dao.HomeEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeEntityDaoConfig;

    private final HomeEntityDao homeEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeEntityDaoConfig = daoConfigMap.get(HomeEntityDao.class).clone();
        homeEntityDaoConfig.initIdentityScope(type);

        homeEntityDao = new HomeEntityDao(homeEntityDaoConfig, this);

        registerDao(HomeEntity.class, homeEntityDao);
    }
    
    public void clear() {
        homeEntityDaoConfig.clearIdentityScope();
    }

    public HomeEntityDao getHomeEntityDao() {
        return homeEntityDao;
    }

}
