package com.liudonghan.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.liudonghan.db.entity.HomeEntity;
import com.liudonghan.db.entity.PetEntity;

import com.liudonghan.db.dao.HomeEntityDao;
import com.liudonghan.db.dao.PetEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeEntityDaoConfig;
    private final DaoConfig petEntityDaoConfig;

    private final HomeEntityDao homeEntityDao;
    private final PetEntityDao petEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeEntityDaoConfig = daoConfigMap.get(HomeEntityDao.class).clone();
        homeEntityDaoConfig.initIdentityScope(type);

        petEntityDaoConfig = daoConfigMap.get(PetEntityDao.class).clone();
        petEntityDaoConfig.initIdentityScope(type);

        homeEntityDao = new HomeEntityDao(homeEntityDaoConfig, this);
        petEntityDao = new PetEntityDao(petEntityDaoConfig, this);

        registerDao(HomeEntity.class, homeEntityDao);
        registerDao(PetEntity.class, petEntityDao);
    }
    
    public void clear() {
        homeEntityDaoConfig.clearIdentityScope();
        petEntityDaoConfig.clearIdentityScope();
    }

    public HomeEntityDao getHomeEntityDao() {
        return homeEntityDao;
    }

    public PetEntityDao getPetEntityDao() {
        return petEntityDao;
    }

}
